name: CD - Deploy with Helm

on:
  workflow_run:
    workflows:
      - CI - Build and Push Microservices
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Verificar cluster de Kubernetes
        shell: powershell
        run: kubectl get nodes

      - name: Desplegar con Helm
        shell: powershell
        run: helm upgrade --install onlineboutique .\helm-chart -n fase2-devops --set images.repository=alejandrovela03 --set images.tag=latest

      - name: Actualizar deployments
        shell: powershell
        run: kubectl rollout restart deployment -n fase2-devops

      - name: Verificar pods
        shell: powershell
        run: kubectl get pods -n fase2-devops